{
  "labels": {
    "backend": "local"
  },
  "platform": "linux/amd64",
  "steps": [
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "secrets": [ "attic_key" ]
    },
    {
      "commands": [
        "nix build '.#nixosConfigurations.ahorn.config.system.build.toplevel' -o 'result-ahorn'"
      ],
      "image": "bash",
      "name": "Build configuration for ahorn"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-ahorn'"
      ],
      "image": "bash",
      "name": "Push result-ahorn to Attic",
      "secrets": [ "attic_key" ]
    },
    {
      "commands": [
        "nix build '.#nixosConfigurations.birne.config.system.build.toplevel' -o 'result-birne'"
      ],
      "image": "bash",
      "name": "Build configuration for birne"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-birne'"
      ],
      "image": "bash",
      "name": "Push result-birne to Attic",
      "secrets": [ "attic_key" ]
    },
    {
      "commands": [
        "nix build '.#nixosConfigurations.kfbox.config.system.build.toplevel' -o 'result-kfbox'"
      ],
      "image": "bash",
      "name": "Build configuration for kfbox"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-kfbox'"
      ],
      "image": "bash",
      "name": "Push result-kfbox to Attic",
      "secrets": [ "attic_key" ]
    },
    {
      "commands": [
        "nix build '.#nixosConfigurations.porree.config.system.build.toplevel' -o 'result-porree'"
      ],
      "image": "bash",
      "name": "Build configuration for porree"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-porree'"
      ],
      "image": "bash",
      "name": "Push result-porree to Attic",
      "secrets": [ "attic_key" ]
    }
  ]
}
